
version: '3.8'

services:
  agent-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: flutterwave/failure-agent:v1
    container_name: flw-failure-agent
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - HF_MODEL_NAME=TinyLlama/TinyLlama-1.1B-Chat-v1.0
      - MAX_NEW_TOKENS=128
      - LOG_LEVEL=INFO
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - model_cache:/app/huggingface_cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  model_cache:
